name: calculadora
description: "Uma calculadora simples escrita em Flutter."
publish_to: 'none'

version: 1.3.0+36

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Dynamic Colors
  dynamic_color: ^1.7.0

# Device Plus
  device_info_plus: ^10.1.1
  
# Email
  flutter_email_sender: ^6.0.3

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master

# Firebase
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_performance: ^0.10.0+4

# HTTP
  http: ^1.2.2

# Math Expressions
  math_expressions: ^2.6.0

# Package Info
  package_info_plus: ^8.0.1

# Path Provider
  path_provider: ^2.1.4

# Provider
  provider: ^6.1.1

# Review  
  in_app_review: ^2.0.9

# Shared Preferences
  shared_preferences: ^2.3.1

# Toast
  fluttertoast: ^8.2.6

# Url Launcher
  url_launcher: ^6.3.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/

fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans.ttf