name: calculadora
description: "Uma calculadora simples escrita em Flutter."
publish_to: 'none'

version: 1.6.4+20250927

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

# Dynamic Colors
  dynamic_color: ^1.7.0

# Device Plus
  device_info_plus: ^12.1.0
  
# Email
  flutter_email_sender: ^8.0.0

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: 5b2c7ae

# Firebase
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  firebase_performance: ^0.11.1

# Google Fonts
  google_fonts: ^6.2.1

# HTTP
  http: ^1.2.2

# Math Expressions
  math_expressions: ^3.1.0

# Package Info
  package_info_plus: ^9.0.0

# Path Provider
  path_provider: ^2.1.5

# Provider
  provider: ^6.1.3

# Review  
  in_app_review: ^2.0.9

# Shared Preferences
  shared_preferences: ^2.3.5

# Toast
  fluttertoast: ^9.0.0

# Url Launcher
  url_launcher: ^6.3.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/