name: calculadora
description: "Uma calculadora simples escrita em Flutter."
publish_to: 'none'

version: 1.2.5+29

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Dynamic Colros
  dynamic_color: ^1.6.9

# Email
  flutter_email_sender: ^6.0.2

# Math Expressions
  math_expressions: ^2.4.0

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master


# Firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8

# HTTP
  http: ^1.2.0

# Package Info
  package_info_plus: ^5.0.1

# Path Provider
  path_provider: ^2.1.2

# Provider
  provider: ^6.1.1

# Review  
  in_app_review: ^2.0.8

# Shared Preferences
  shared_preferences: ^2.2.2

# Url Launcher
  url_launcher: ^6.2.4

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/img/