name: calculadora
description: Uma calculadora simples escrita em Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.4+28

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Dynamic Colros
  dynamic_color: ^1.6.9

# Math Expressions
  math_expressions: ^2.4.0

# Firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8

# Provider
  provider: ^6.1.1

# Shared Preferences
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
