// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2kwu2jTrGWF1mDW-s7p_vN8W0_d7u0B4',
    appId: '1:573885901268:android:bd99f381e650e2fb864e41',
    messagingSenderId: '573885901268',
    projectId: 'calculadora-app-a7506',
    storageBucket: 'calculadora-app-a7506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1yKKOZTvMVfIqlmIhaC9XhAOaSUt26A',
    appId: '1:573885901268:ios:35ef794c976aedf4864e41',
    messagingSenderId: '573885901268',
    projectId: 'calculadora-app-a7506',
    storageBucket: 'calculadora-app-a7506.appspot.com',
    iosBundleId: 'com.github.hendrilmendes.calculadora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ1yKKOZTvMVfIqlmIhaC9XhAOaSUt26A',
    appId: '1:573885901268:ios:6cad60ad28667314864e41',
    messagingSenderId: '573885901268',
    projectId: 'calculadora-app-a7506',
    storageBucket: 'calculadora-app-a7506.appspot.com',
    iosBundleId: 'com.github.hendrilmendes.calculadora.RunnerTests',
  );
}
